parameters:
    ehdev.basics.entity.simplecontact.class: EHDev\Bundle\BasicsBundle\Entity\SimpleContact
    ehdev.basics.entity.simplecontactaddress.class: EHDev\Bundle\BasicsBundle\Entity\SimpleContactAddress

    ehdev.basics.simplecontact.manager.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

services:
    ehdev.basics.simplecontact.manager:
        class: %ehdev.basics.simplecontact.manager.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %ehdev.basics.entity.simplecontact.class%
            - "@doctrine.orm.entity_manager"
