datagrids:
    ehdev-basics-simplecontact-grid:
        extended_entity_name: "%ehdev.basics.entity.simplecontact.class%"
        acl_resource: ehdev_basics_simplecontact_view
        source:
            type: orm
            query:
                select:
                    - sc.id
                    - sc.firstName
                    - sc.lastName
                    - sc.createdAt
                    - sc.updatedAt
                    - sc.skype
                    - sc.twitter
                    - sc.facebook
                    - sc.birthday
                    - sc.gender
                    - sc.email
                    - sc.phone
                from:
                    - { table: "%ehdev.basics.entity.simplecontact.class%", alias: sc }
                join:
                    left:
                        - { join: sc.address, alias: address }
        columns:
            id:
                label:         ehdev.basics.simplecontact.id.label
            firstName:
                frontend_type: string
                label:         ehdev.basics.simplecontact.first_name.label
            lastName:
                frontend_type: string
                label:         ehdev.basics.simplecontact.last_name.label
            email:
                frontend_type: string
                label:         ehdev.basics.simplecontact.email.label
            phone:
                frontend_type: string
                label:         ehdev.basics.simplecontact.phone.label
            birthday:
                frontend_type: datetime
                label:         ehdev.basics.simplecontact.birthday.label
            skype:
                frontend_type: string
                label:         ehdev.basics.simplecontact.skype.label
            twitter:
                frontend_type: string
                label:         ehdev.basics.simplecontact.twitter.label
            facebook:
                frontend_type: string
                label:         ehdev.basics.simplecontact.facebook.label
            gender:
                label:         ehdev.basics.simplecontact.gender.label
                frontend_type: select
                choices: "@oro_user.gender_provider->getChoices"
                renderable: false
            createdAt:
                frontend_type: datetime
                label:         oro.ui.created_at
            updatedAt:
                frontend_type: datetime
                label:         oro.ui.updated_at
        filters:
            columns:
                firstName:
                    type: string
                    data_name: c.firstName
                lastName:
                    type: string
                    data_name: c.lastName
                birthday:
                    type: date
                    data_name: c.birthday
                    enabled: false
                gender:
                    type: choice
                    data_name: c.gender
                    options:
                        field_options:
                            choices: "@oro_user.gender_provider->getChoices"
                    enabled: false
                email:
                    type: string
                    data_name: email.email
        properties:
            id: ~
#            view_link:
#                type: url
#                route: ehdev_basics_simplecontact_view
#                params: [ id ]
            update_link:
                type:       url
                route:      ehdev_basics_simplecontact_update
                params:     [ id ]
            delete_link:
                type: url
                route: oro_api_delete_simplecontact
                params: [ id ]
        actions:
#            view:
#                type: navigate
#                label: oro.grid.action.view
#                icon: eye
#                link: view_link
#                rowAction: true
            update:
                type: dialog
                label: oro.grid.action.update
                icon: edit
                link: update_link
                widgetOptions:
                    reload-grid-name: ehdev-basics-simplecontact-grid
                    options:
                        dialogOptions:
                            title:  "@translator->trans(ehdev.basics.simplecontact.widget.edit.title)"
                            modal:  true
                            width:  700
            delete:
                type:          delete
                acl_resource:  ehdev_basics_simplecontact_delete
                label:         oro.grid.action.delete
                icon:          trash
                link:          delete_link
