services:
    ehdev_basics.form.type.oro_user_email_select:
        class: EHDev\BasicsBundle\Form\Type\OroUserEmailOriginSelectType
        tags:
            - { name: form.type, alias: ehdev_oro_user_email_origin_select }
